# Generated by Django 3.2.13 on 2022-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluedivis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='is_bluechip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dweet',
            name='is_champion',
            field=models.BooleanField(default=False),
        ),
    ]
